// API Endpoints matching the Express.js backend routes
export const API_ENDPOINTS = {
  AUTH: {
    SIGNUP: "/auth/signup",
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    ME: "/auth/me",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    REFRESH: "/auth/refresh",
    RESEND_VERIFICATION: "/auth/resend-verification",
  },
  USER: {
    GET_PROFILE: "/users/profile",
    UPDATE_PROFILE: "/users/profile",
    PUSH_TOKEN: "/users/push-token",
    DELETE_ACCOUNT: "/users/account",
    SWITCH_ROLE: "/users/role",
  },
  NOTIFICATION: {
    LIST: "/notifications",
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    DELETE: (id: string) => `/notifications/${id}`,
  },
  FOOD: {
    LIST_MINE: "/foods/mine",
    CREATE_DONATION: "/foods/donations",
    GET_ALL_DONATIONS: "/foods/donations",
    GET_DONATION_BY_ID: (foodID: string) => `/foods/donations/${foodID}`,
    GET_DONATIONS_BY_USER: (userID: string) =>
      `/foods/donations/user/${userID}`,
    UPDATE_DONATION: (foodID: string) => `/foods/donations/${foodID}`,
    DELETE_DONATION: (foodID: string) => `/foods/donations/${foodID}`,
    REQUEST_DONATION: "/foods/donations/request",
    GET_BY_ID: (foodID: string) => `/foods/${foodID}`,
    ADD_DONATION: "/foods/donations",
  },
  LOCATION: {
    CREATE: "/locations",
    LIST_MINE: "/locations/mine",
    LIST_FOR_FOOD: (foodID: string) => `/locations/food/${foodID}`,
    UPDATE: (locID: string) => `/locations/${locID}`,
    DELETE: (locID: string) => `/locations/${locID}`,
  },
  DISTRIBUTION: {
    CREATE: "/distributions",
    GET_ALL: "/distributions",
    GET_MINE: "/distributions/mine",
    GET_AVAILABLE: "/distributions/available",
    CLAIM_LIMITS: "/distributions/claim-limits",
    GET_BY_ID: (disID: string) => `/distributions/${disID}`,
    UPDATE: (disID: string) => `/distributions/${disID}`,
    UPDATE_STATUS: (disID: string) => `/distributions/${disID}/status`,
    COMPLETE: (disID: string) => `/distributions/${disID}/complete`,
    REQUEST: (disID: string) => `/distributions/${disID}/request`,
    ON_THE_WAY: (disID: string) => `/distributions/${disID}/on-the-way`,
  },
  FEEDBACK: {
    CREATE: "/feedback",
    LIST_FOR_DISTRIBUTION: (disID: string) => `/feedback/distribution/${disID}`,
    UPDATE: (feedbackID: string) => `/feedback/${feedbackID}`,
    LIST_RECEIVED: "/feedback/received",
  },
  DASHBOARD: {
    DONOR: "/dashboard/donor",
    RECIPIENT: "/dashboard/recipient",
    BROWSE: "/dashboard/browse",
  },
};
